spring:
  datasource:
    name: mydb
    type: org.apache.commons.dbcp.BasicDataSource
    url: jdbc:mysql://localhost:3306/paas?useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
    username: root
    password: lm123456
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 10
    maxActive: 30
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
server:
  port: 8081
